// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB4kgC_NaIdb84WlZ1ukOcLF5wXrIssvBo',
    appId: '1:403171721076:web:7b4de87f6e19c440b6b621',
    messagingSenderId: '403171721076',
    projectId: 'flutter-otp-67618',
    authDomain: 'flutter-otp-67618.firebaseapp.com',
    storageBucket: 'flutter-otp-67618.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyApeCYAZLeX3l3iiJ-I-L3k7VGnljbzj1U',
    appId: '1:403171721076:android:10a1e4cf82eae7a0b6b621',
    messagingSenderId: '403171721076',
    projectId: 'flutter-otp-67618',
    storageBucket: 'flutter-otp-67618.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDYyiEqvd-zNO2dY0uwhU_uyKJVHeZwxAA',
    appId: '1:403171721076:ios:69d3a41fb3764b3db6b621',
    messagingSenderId: '403171721076',
    projectId: 'flutter-otp-67618',
    storageBucket: 'flutter-otp-67618.appspot.com',
    androidClientId: '403171721076-r235912t9vcn5elqiof2of8f5l03c1s8.apps.googleusercontent.com',
    iosClientId: '403171721076-o78nav0v6sjftce0g20vmho4lbumgfm9.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterOtp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDYyiEqvd-zNO2dY0uwhU_uyKJVHeZwxAA',
    appId: '1:403171721076:ios:69d3a41fb3764b3db6b621',
    messagingSenderId: '403171721076',
    projectId: 'flutter-otp-67618',
    storageBucket: 'flutter-otp-67618.appspot.com',
    androidClientId: '403171721076-r235912t9vcn5elqiof2of8f5l03c1s8.apps.googleusercontent.com',
    iosClientId: '403171721076-o78nav0v6sjftce0g20vmho4lbumgfm9.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterOtp',
  );
}
